<a href="https://colab.research.google.com/github/Oxter12a/Oxter12a/blob/main/HeartDisease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing libraries


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


#importing datasets


In [7]:
dataset=pd.read_csv('heart.csv')
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values

In [6]:
print(X)

[[52.  1.  0. ...  2.  2.  3.]
 [53.  1.  0. ...  0.  0.  3.]
 [70.  1.  0. ...  0.  0.  3.]
 ...
 [47.  1.  0. ...  1.  1.  2.]
 [50.  0.  0. ...  2.  0.  2.]
 [54.  1.  0. ...  1.  1.  3.]]


In [8]:
print(Y)

[0 0 0 ... 0 1 0]


#Data pre-processing


In [9]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
le2=LabelEncoder()
le6=LabelEncoder()
le8=LabelEncoder()
le10=LabelEncoder()
X[:,1]=le1.fit_transform(X[:,1])
X[:,2]=le2.fit_transform(X[:,2])
X[:,6]=le6.fit_transform(X[:,6])
X[:,8]=le8.fit_transform(X[:,8])
X[:,10]=le10.fit_transform(X[:,10])

In [10]:
print(X)

[[52.  1.  0. ...  2.  2.  3.]
 [53.  1.  0. ...  0.  0.  3.]
 [70.  1.  0. ...  0.  0.  3.]
 ...
 [47.  1.  0. ...  1.  1.  2.]
 [50.  0.  0. ...  2.  0.  2.]
 [54.  1.  0. ...  1.  1.  3.]]
